# Generated by Django 2.2.4 on 2019-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ManyToManyField(to='vendors.Vendor'),
        ),
    ]
