# Generated by Django 2.2.4 on 2019-09-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customized', models.BooleanField(default=False)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendors.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('total_credits', models.IntegerField()),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
                ('menus', models.ManyToManyField(to='users.OrderMenu')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('current_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.OrderMenu')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'HOME'), ('2', 'OFFICE'), ('3', 'OTHER')], max_length=1)),
                ('flat_no', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
    ]
